### ISSUE TITLE
Wrong namespace

### ISSUE THREAD

**Issue by robbanl** [globalvisionmedia/oauth2-harvest#1]
https://github.com/globalvisionmedia/oauth2-harvest/blob/main/src/Provider/Harvest.php#L6

https://github.com/globalvisionmedia/oauth2-harvest/blob/main/src/Provider/Exception/HarvestIdentityProviderException.php#L3

**Comment by globalvisionmedia** [comment]
this looks correct to me? Can you provide more information please?

**Comment by robbanl** [comment]
Hi!Of course. Look at the third segment, Client vs HarvestClient. I noticed it when trying to integrate inside a Laravel application :-)

GlobalVisionMedia\OAuth2\**Client**\Provider\Exception\HarvestIdentityProviderException;
GlobalVisionMedia\OAuth2\**HarvestClient**\Provider\Exception;

**Comment by globalvisionmedia** [comment]
Fixed. Thanks!

**Comment by robbanl** [comment]
Sweet :-) Thank you for a fast fix! Sorry I wasn't clear enough, long work day :-)

**Comment by globalvisionmedia** [comment]
No worries

Peter Hawkins
Managing Director
Global Vision
Suite 303, 517 Flinders Lane Melbourne 3000


(p) 1300 201 866 (m) 0414 674 666 (d) 03 9966 3879
http://www.gvmedia.com.au
________________________________

**Comment by robbanl** [comment]
@globalvisionmedia Don't forget to tag a new version :-)
